### ISSUE TITLE
/bank_accounts

### ISSUE THREAD

**Issue by watzing** [thephpleague/omnipay-pin#14]
Is there any plan to add other features of the API to this library? In particular creating a recipient and creating a transfer? Or is that beyond the scope of this library?

Thanks!

**Comment by delatbabel** [comment]
Generally speaking it's only the scope of omnipay to handle inwards payments not outwards payments. However there is no reason that additional functionality should not be merged in if you had a PR to contribute. Please adhere to the existing standards -- documentation, code quality, testing etc.
