### ISSUE TITLE
Recipient registration not supported

### ISSUE THREAD

**Issue by rahulsharma416** [thephpleague/omnipay-pin#16]
Following API's are not supported regarding Pin Payments:
> Recipient registration
> Bank Account registration
> Fund transfer to a bank account

If it is supported then there is not documentation of the same on the Omnipay-pin readme doc.

**Comment by delatbabel** [comment]
Generally speaking, Omnipay is a library that supports payment processing (money inwards). It does not support money outwards processing.  All of the functions you have listed above are money outwards processing and don't really belong in Omnipay.

Ideally there would be a separate "money outwards" library that supported sending money via various methods -- gateways, bank transfers, Western Union, PayPal, PIN, bitcoin, etc, however Omnipay is not that library.

You could choose to send a PR for that functionality above as a coding exercise or if you needed that functionality specifically for PIN transactions, but it would not be core Omnipay functionality and the number of Omnipay users who would use, test, and maintain that functionality would probably be limited.
